{% set name = "km3db" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/km3db-{{ version }}.tar.gz
  sha256: e7dc41cf1bf4467f1ecd596fe483073ec6db369ecc5a0a796ce6ab8109bd378e

build:
  number: 0
  noarch: python
  entry_points:
    - km3db=km3db.cli.km3db:main
    - streamds=km3db.cli.streamds:main
    - detx=km3db.cli.detx:main
    - runtable=km3db.cli.runtable:main
    - runinfo=km3db.cli.runinfo:main
    - wtd=km3db.cli.wtd:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools_scm
  run:
    - docopt
    - python >=2.7
    - pytz
    - requests
    - setuptools-scm

test:
  imports:
    - km3db
  commands:
    - pip check
    - km3db --help
    - streamds --help
    - detx --help
    - runtable --help
    - runinfo --help
    - wtd --help
  requires:
    - pip

about:
  home: https://git.km3net.de/km3py/km3db
  summary: KM3NeT database library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tamasgal
